### ISSUE TITLE
read: connection reset by peer error

### ISSUE THREAD

**Issue by carterpage** [staticmukesh/opentsdb-load-generator#1]
This code doesn't send new lines, resulting in org.jboss.netty.handler.codec.frame.TooLongFrameException on the opentsdb server.

https://github.com/staticmukesh/opentsdb-load-generator/blob/9d7b1c38611546551aa0ab1cb871915feb67f78f/main.go#L64

**Comment by staticmukesh** [comment]
Thanks for noticing the issue.
